version: "3"
services:
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gbt
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db


volumes:
  db_data:
